server:
  port: 8050
  servlet:
    context-path: /data

spring:
  application:
    name: data-provider-service
  profiles:
    active: test
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://uaa:8090/uaa/token_keys


eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: http://localhost:9000/eureka #In the following server

