server:
  port: 8050

spring:
  webflux:
    base-path: /data
  application:
    name: data-provider-service
  profiles:
    active: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/GameManager

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9000}/eureka #In the following server

