version: "3.8"
services:

  redis:
    image: redis:6.2.4
    container_name: redis
    ports:
      - 6379:6379

  keycloak:
    image: jboss/keycloak:13.0.0
    container_name: "keycloak"
    volumes:
      - ./platform-config/keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080

  #services TODO
