version: "3.8"
services:

  #Services
  redis:
    image: redis:6.2.4
    container_name: redis
    ports:
      - 6379:6379

  keycloak:
    image: jboss/keycloak:13.0.0
    container_name: "keycloak"
    volumes:
      - ./platform-config/keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: h2
    ports:
      - 8080:8080

  #Applications
  eureka:
    image: eureka-server:latest
    container_name: eureka
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      - EUREKA_SERVER=http://eureka:9000
      - EUREKA_HOST=eureka

  gateway:
    image: api-gateway:latest
    container_name: gateway
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - keycloak
      - eureka
#      - app-service
    environment:
      - KEYCLOAK_URL=http://192.168.0.85:8080
      - EUREKA_SERVER=http://eureka:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

#  mobile-gateway:
#    image: mobile-api-gateway:latest
#    container_name: mobile-gateway
#    expose:
#      - "8083"
#    ports:
#      - "8083:8083"
#    depends_on:
#      - keycloak
#      - eureka
#    environment:
#      - KEYCLOAK_URL=http://192.168.0.85:8080
#      - EUREKA_SERVER=http://eureka:9000
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

  data-service:
    image: data-service:latest
    container_name: data-service
    expose:
      - "8050"
    ports:
      - "8050:8050"
    depends_on:
      - eureka
      - keycloak
    environment:
      - KEYCLOAK_URL=http://192.168.0.85:8080
      - EUREKA_SERVER=http://eureka:9000

  app-service:
    image: app-service:latest
    container_name: app-service
    expose:
      - "8045"
    ports:
      - "8045:8045"
    depends_on:
      - eureka
      - keycloak
    environment:
      - KEYCLOAK_URL=http://192.168.0.85:8080
      - EUREKA_SERVER=http://eureka:9000

  forum-service:
    image: forum-service:latest
    container_name: forum-service
    expose:
      - "8030"
    ports:
      - "8030:8030"
    depends_on:
      - eureka
      - keycloak
    environment:
      - KEYCLOAK_URL=http://192.168.0.85:8080
      - EUREKA_SERVER=http://eureka:9000

  scoreboard-service:
    image: scoreboard-service:latest
    container_name: scoreboard-service
    expose:
      - "8099"
    ports:
      - "8099:8099"
    depends_on:
      - eureka
      - keycloak
    environment:
      - KEYCLOAK_URL=http://192.168.0.85:8080
      - EUREKA_SERVER=http://eureka:9000


  desktop-client:
    image: desktop-client:latest
    container_name: desktop-client
    expose:
      - "4200"
    ports:
      - "4200:4200"


  prometheus:
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './platform-config/prometheus/prometheus.yml:/etc/prometheus/config.yml'

  grafana:
    image: 'grafana/grafana:6.5.0'
    ports:
      - '3000:3000'