server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: app-provider-service
          uri: lb://APP-PROVIDER-SERVICE
          predicates:
            - Path=/app/**
        - id: data-provider-service
          uri: lb://DATA-PROVIDER-SERVICE
          predicates:
            - Path=/data/**
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.requestedTokens: 1

management:
  health:
    redis:
      enabled: true

jwt:
  secretKey: secret

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
