server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : app-provider-service
          uri: http://localhost:8045
          predicates:
            - Path=/app/**
        - id: data-provider-service
          uri: http://localhost:8050
          predicates:
            - Path=/data/**
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
