server:
  port: 8082

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
#            enable-cors: true
            client-id: api-gateway
            client-secret: 580009c1-079c-41c7-9ab7-28d1cc2eda3d
            scope: openid
        provider:
          keycloak:
#            enable-cors: true
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/GameManager
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
      routes:
        - id: app-provider-service
          uri: lb://APP-PROVIDER-SERVICE
          predicates:
            - Path=/app/**
        - id: data-provider-service
          uri: lb://DATA-PROVIDER-SERVICE
          predicates:
            - Path=/data/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 2
#                redis-rate-limiter.burstCapacity: 2
#                redis-rate-limiter.requestedTokens: 1

management:
  health:
    redis:
      enabled: true

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9000}/eureka
