server:
  port: 8099

spring:
  application:
    name: scoreboard-service
  webflux:
    base-path: /scoreboard

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/GameManager
  r2dbc:
    url: r2dbc:h2:mem:///forum?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9000}/eureka #In the following server