server:
  port: 8045

spring:
  codec:
    max-in-memory-size: 2MB
  application:
    name: app-provider-service
  webflux:
    base-path: /app
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/GameManager
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
#  jpa:
#    hibernate:
#      ddl-auto: update
#  servlet:
#    multipart:
#      max-file-size: 2MB

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9000}/eureka #In the following server
