server:
  port: 8045
  servlet:
    context-path: /app

spring:
  application:
    name: app-provider-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://uaa:8090/uaa/token_keys


eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: http://localhost:9000/eureka #In the following server
