server:
  port: 8045
  servlet:
    context-path: /app

spring:
  application:
    name: app-provider-service
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9000}/eureka #In the following server
