server:
  port: 8045
  servlet:
    context-path: /app

spring:
  application:
    name: app-provider-service
  profiles:
    active: test

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true #Register the service to the Eureka server
    service-url:
      defaultZone: http://localhost:9000/eureka #In the following server
