server:
  port: 8044

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: test-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/GameManager
